// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for about documents
 */
interface AboutDocumentData {
	/**
	 * about_me field in *about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.about_me
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	about_me: prismic.KeyTextField;
	
	/**
	 * name field in *about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * presentation field in *about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.presentation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	presentation: prismic.KeyTextField;
	
	/**
	 * experience field in *about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.experience
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	experience: prismic.KeyTextField;
	
	/**
	 * motivational field in *about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.motivational
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	motivational: prismic.KeyTextField;
	
	/**
	 * title_resume field in *about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.title_resume
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title_resume: prismic.KeyTextField;
	
	/**
	 * resume field in *about*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.resume
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	resume: prismic.RichTextField;
	
	/**
	 * image_person field in *about*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.image_person
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_person: prismic.ImageField<never>;
	
	/**
	 * graduation field in *about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.graduation
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	graduation: prismic.KeyTextField;
}

/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *contact → contacts*
 */
export interface ContactDocumentDataContactsItem {
	/**
	 * link field in *contact → contacts*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.contacts[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
	
	/**
	 * label_contact field in *contact → contacts*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.contacts[].label_contact
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label_contact: prismic.KeyTextField;
}

/**
 * Content for contact documents
 */
interface ContactDocumentData {
	/**
	 * title field in *contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * subtitle field in *contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * contacts field in *contact*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.contacts[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	contacts: prismic.GroupField<Simplify<ContactDocumentDataContactsItem>>;
}

/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ContactDocumentData>, "contact", Lang>;

/**
 * Content for courses documents
 */
interface CoursesDocumentData {
	/**
	 * title field in *courses*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: courses.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * completion_period field in *courses*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: courses.completion_period
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	completion_period: prismic.KeyTextField;
	
	/**
	 * certificates_link field in *courses*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: courses.certificates_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	certificates_link: prismic.LinkField;
	
	/**
	 * resume field in *courses*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: courses.resume
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	resume: prismic.RichTextField;
	
	/**
	 * achievement_platform field in *courses*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: courses.achievement_platform
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	achievement_platform: prismic.KeyTextField;
	
	/**
	 * workload field in *courses*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: courses.workload
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	workload: prismic.KeyTextField;
	
	/**
	 * certificate_image field in *courses*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: courses.certificate_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	certificate_image: prismic.ImageField<never>;
}

/**
 * courses document from Prismic
 *
 * - **API ID**: `courses`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoursesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<CoursesDocumentData>, "courses", Lang>;

/**
 * Content for experience_list documents
 */
interface ExperienceListDocumentData {
	/**
	 * enterprise field in *experience_list*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_list.enterprise
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	enterprise: prismic.KeyTextField;
	
	/**
	 * entry_year field in *experience_list*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_list.entry_year
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	entry_year: prismic.KeyTextField;
	
	/**
	 * exit_year field in *experience_list*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_list.exit_year
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	exit_year: prismic.KeyTextField;
	
	/**
	 * function field in *experience_list*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_list.function
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	function: prismic.KeyTextField;
	
	/**
	 * description_function field in *experience_list*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_list.description_function
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description_function: prismic.RichTextField;
	
	/**
	 * link_enterprise field in *experience_list*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_list.link_enterprise
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_enterprise: prismic.KeyTextField;
}

/**
 * experience_list document from Prismic
 *
 * - **API ID**: `experience_list`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceListDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ExperienceListDocumentData>, "experience_list", Lang>;

/**
 * Content for experience work documents
 */
interface ExperienceWorkDocumentData {
	/**
	 * title field in *experience work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_work.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * subtitle field in *experience work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_work.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * entry_year field in *experience work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_work.entry_year
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	entry_year: prismic.KeyTextField;
	
	/**
	 * exit_year field in *experience work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_work.exit_year
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	exit_year: prismic.KeyTextField;
	
	/**
	 * function field in *experience work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_work.function
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	function: prismic.KeyTextField;
	
	/**
	 * description_function field in *experience work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_work.description_function
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description_function: prismic.KeyTextField;
	
	/**
	 * location field in *experience work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_work.location
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	location: prismic.KeyTextField;
}

/**
 * experience work document from Prismic
 *
 * - **API ID**: `experience_work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceWorkDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ExperienceWorkDocumentData>, "experience_work", Lang>;

/**
 * Item in *experience → work_experience*
 */
export interface ExperienceDocumentDataWorkExperienceItem {
	/**
	 * entry_year field in *experience → work_experience*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.work_experience[].entry_year
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	entry_year: prismic.KeyTextField;
	
	/**
	 * exit_year field in *experience → work_experience*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.work_experience[].exit_year
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	exit_year: prismic.KeyTextField;
	
	/**
	 * function field in *experience → work_experience*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.work_experience[].function
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	function: prismic.KeyTextField;
	
	/**
	 * description_function field in *experience → work_experience*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.work_experience[].description_function
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description_function: prismic.KeyTextField;
	
	/**
	 * link field in *experience → work_experience*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.work_experience[].link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link: prismic.KeyTextField;
}

/**
 * Content for experience documents
 */
interface ExperienceDocumentData {
	/**
	 * title field in *experience*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * subtitle field in *experience*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * work_experience field in *experience*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience.work_experience[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	work_experience: prismic.GroupField<Simplify<ExperienceDocumentDataWorkExperienceItem>>;
}

/**
 * experience document from Prismic
 *
 * - **API ID**: `experience`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ExperienceDocumentData>, "experience", Lang>;

/**
 * Item in *home_hero → presentation_area*
 */
export interface HomeHeroDocumentDataPresentationAreaItem {
	/**
	 * comment field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].comment
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	comment: prismic.KeyTextField;
	
	/**
	 * title field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * open field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].open
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	open: prismic.KeyTextField;
	
	/**
	 * label_function field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].label_function
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label_function: prismic.KeyTextField;
	
	/**
	 * content_function field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].content_function
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	content_function: prismic.KeyTextField;
	
	/**
	 * label_level field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].label_level
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label_level: prismic.KeyTextField;
	
	/**
	 * content_level field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].content_level
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	content_level: prismic.KeyTextField;
	
	/**
	 * close field in *home_hero → presentation_area*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[].close
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	close: prismic.KeyTextField;
}

/**
 * Item in *home_hero → presentation_skills*
 */
export interface HomeHeroDocumentDataPresentationSkillsItem {
	/**
	 * title field in *home_hero → presentation_skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * open field in *home_hero → presentation_skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[].open
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	open: prismic.KeyTextField;
	
	/**
	 * label_tech_stack field in *home_hero → presentation_skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[].label_tech_stack
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label_tech_stack: prismic.KeyTextField;
	
	/**
	 * content_tech_stack field in *home_hero → presentation_skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[].content_tech_stack
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	content_tech_stack: prismic.KeyTextField;
	
	/**
	 * label_frameworks field in *home_hero → presentation_skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[].label_frameworks
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label_frameworks: prismic.KeyTextField;
	
	/**
	 * content_frameworks field in *home_hero → presentation_skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[].content_frameworks
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	content_frameworks: prismic.KeyTextField;
	
	/**
	 * close field in *home_hero → presentation_skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[].close
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	close: prismic.KeyTextField;
}

/**
 * Item in *home_hero → about*
 */
export interface HomeHeroDocumentDataAboutItem {
	/**
	 * open field in *home_hero → about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.about[].open
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	open: prismic.KeyTextField;
	
	/**
	 * title field in *home_hero → about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.about[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * label field in *home_hero → about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.about[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * close field in *home_hero → about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.about[].close
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	close: prismic.KeyTextField;
	
	/**
	 * resume field in *home_hero → about*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.about[].resume
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	resume: prismic.KeyTextField;
}

/**
 * Content for home_hero documents
 */
interface HomeHeroDocumentData {
	/**
	 * photo field in *home_hero*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.photo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	photo: prismic.ImageField<never>;
	
	/**
	 * title field in *home_hero*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * subtitle field in *home_hero*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * presentation_area field in *home_hero*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_area[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	presentation_area: prismic.GroupField<Simplify<HomeHeroDocumentDataPresentationAreaItem>>;
	
	/**
	 * presentation_skills field in *home_hero*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.presentation_skills[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	presentation_skills: prismic.GroupField<Simplify<HomeHeroDocumentDataPresentationSkillsItem>>;
	
	/**
	 * about field in *home_hero*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_hero.about[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	about: prismic.GroupField<Simplify<HomeHeroDocumentDataAboutItem>>;
}

/**
 * home_hero document from Prismic
 *
 * - **API ID**: `home_hero`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeHeroDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomeHeroDocumentData>, "home_hero", Lang>;

/**
 * Content for jobs documents
 */
interface JobsDocumentData {
	/**
	 * Title field in *jobs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *jobs*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
	
	/**
	 * type field in *jobs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.type
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	type: prismic.KeyTextField;
	
	/**
	 * Project Link field in *jobs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.project_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	project_link: prismic.KeyTextField;
	
	/**
	 * Thumb field in *jobs*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.thumb
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumb: prismic.ImageField<never>;
}

/**
 * jobs document from Prismic
 *
 * - **API ID**: `jobs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<JobsDocumentData>, "jobs", Lang>;

/**
 * Content for projects documents
 */
interface ProjectsDocumentData {
	/**
	 * Title field in *projects*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *projects*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * type field in *projects*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.type
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	type: prismic.KeyTextField;
	
	/**
	 * Project Link field in *projects*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.project_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project_link: prismic.LinkField;
	
	/**
	 * Thumb field in *projects*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.thumb
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumb: prismic.ImageField<never>;
}

/**
 * projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ProjectsDocumentData>, "projects", Lang>;

/**
 * Item in *skills → skills*
 */
export interface SkillsDocumentDataSkillsItem {
	/**
	 * logo_skill field in *skills → skills*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: skills.skills[].logo_skill
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo_skill: prismic.ImageField<never>;
	
	/**
	 * name_skill field in *skills → skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: skills.skills[].name_skill
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name_skill: prismic.KeyTextField;
}

/**
 * Content for skills documents
 */
interface SkillsDocumentData {
	/**
	 * skills_title field in *skills*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: skills.skills_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	skills_title: prismic.KeyTextField;
	
	/**
	 * skills field in *skills*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: skills.skills[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	skills: prismic.GroupField<Simplify<SkillsDocumentDataSkillsItem>>;
}

/**
 * skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SkillsDocumentData>, "skills", Lang>;

export type AllDocumentTypes = AboutDocument | ContactDocument | CoursesDocument | ExperienceListDocument | ExperienceWorkDocument | ExperienceDocument | HomeHeroDocument | JobsDocument | ProjectsDocument | SkillsDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismicClient.ClientConfig): prismicClient.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			AboutDocument,
			AboutDocumentData,
			ContactDocument,
			ContactDocumentData,
			ContactDocumentDataContactsItem,
			CoursesDocument,
			CoursesDocumentData,
			ExperienceListDocument,
			ExperienceListDocumentData,
			ExperienceWorkDocument,
			ExperienceWorkDocumentData,
			ExperienceDocument,
			ExperienceDocumentData,
			ExperienceDocumentDataWorkExperienceItem,
			HomeHeroDocument,
			HomeHeroDocumentData,
			HomeHeroDocumentDataPresentationAreaItem,
			HomeHeroDocumentDataPresentationSkillsItem,
			HomeHeroDocumentDataAboutItem,
			JobsDocument,
			JobsDocumentData,
			ProjectsDocument,
			ProjectsDocumentData,
			SkillsDocument,
			SkillsDocumentData,
			SkillsDocumentDataSkillsItem,
			AllDocumentTypes
		}
	}
}